spring:
  jackson:
    deserialization:
      failOnUnknownProperties: true
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
  ## 쿼리가 보여줄 때 실제 입력되는 값을 보고 싶은 경우
  org.hibernate.type.descriptor.sql.BasicBinder: trace